language: objective-c
before_install: gem install cocoapods
script:
- xctool -workspace TravisTestApp.xcworkspace -scheme TravisTestApp -sdk iphoneos
  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
- xctool -workspace TravisTestApp.xcworkspace -scheme TravisTestApp -sdk iphonesimulator
  build test -freshInstall -freshSimulator
env:
  global:
  - APP_NAME="TravisTestApp"
  - 'DEVELOPER_NAME="iPhone Distribution: Tailored Media Gmbh (22DEN472RY)"'
  - PROFILE_NAME="Travis_Test_App_inHouse"
  - secure: PS1XonfvpBgaSoClKhZ0LjV+aDOIzPP6MdYXmYWAFNT1YEkA+l17lHAgIsZzmV3iVAylIjzz5yshWg5SR+4XvfWXfbwhE1YhVdWwVUsWHNjjFR9q6e7dc9i3R+Kfc1Kj8XJIWrMS0u8VACWtICIOquo0HlowldGb47lq9Qddbkw=
  - secure: DTgE2jYf6U7i3dFxXl6W1X1PqZ7XUiXx0jJeCCvC8Ab303UqNGU8e5PXIpBUHmivoeu/uPgGkC9MHyoNKqyRFKr1e6pVsvwsNrJjoiAj25oHeKfYqmZML4q52DDS8Z1sulwPsbtDDno2khtO6HsP3AidvYYKrctL7u0nE2pZVGE=
  - secure: HCORozu+NrIWbB0NuGKwDNUPiXul9jbMoYpXELa16byB18tCJgEc/cpZ0VGPDgCVqW6UG4NR2CHHtivmORgMdGVqfDTNX/3TicIgMtxw+S3Rp1vRQT+Uqd0afANZa+phP5jpwu0hn8eCxBVV/mWYRrchoda85oKEL/JWJwkA6TI=
  - secure: VzBYTfW3IGm1Uz835aFSAsTcQjSkzWGACYD9em6IFzhLNFuzHxCTSv6oICRMgAKDF+IuUvDR6tdRPUNceGGFKVMPp4cFTnKKIILF5/Vyz1PVYOPiNM3yftqEZdMA18o0uNplpGztk2pXx07Ptmrm+8h0rMkBaWGQteedw62ljjw=
before_script:
- openssl aes-256-cbc -k "$ENCPWD" -in scripts/profile/Travis_Test_App_inHouse.mobileprovision.enc
  -d -a -out scripts/profile/Travis_Test_App_inHouse.mobileprovision
- openssl aes-256-cbc -k "$ENCPWD" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCPWD" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
after_success:
- ./scripts/sign.sh
after_script:
- ./scripts/clean.sh
